#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jwelleryshopping.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Project_demo")]
	public partial class dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdminLoginMst(AdminLoginMst instance);
    partial void UpdateAdminLoginMst(AdminLoginMst instance);
    partial void DeleteAdminLoginMst(AdminLoginMst instance);
    partial void InsertBrandMst(BrandMst instance);
    partial void UpdateBrandMst(BrandMst instance);
    partial void DeleteBrandMst(BrandMst instance);
    partial void InsertCartList(CartList instance);
    partial void UpdateCartList(CartList instance);
    partial void DeleteCartList(CartList instance);
    partial void InsertCatMst(CatMst instance);
    partial void UpdateCatMst(CatMst instance);
    partial void DeleteCatMst(CatMst instance);
    partial void InsertCertifyMst(CertifyMst instance);
    partial void UpdateCertifyMst(CertifyMst instance);
    partial void DeleteCertifyMst(CertifyMst instance);
    partial void InsertDimInfoMst(DimInfoMst instance);
    partial void UpdateDimInfoMst(DimInfoMst instance);
    partial void DeleteDimInfoMst(DimInfoMst instance);
    partial void InsertDimQltyMst(DimQltyMst instance);
    partial void UpdateDimQltyMst(DimQltyMst instance);
    partial void DeleteDimQltyMst(DimQltyMst instance);
    partial void InsertDimQltySubMst(DimQltySubMst instance);
    partial void UpdateDimQltySubMst(DimQltySubMst instance);
    partial void DeleteDimQltySubMst(DimQltySubMst instance);
    partial void InsertGoldKrtMst(GoldKrtMst instance);
    partial void UpdateGoldKrtMst(GoldKrtMst instance);
    partial void DeleteGoldKrtMst(GoldKrtMst instance);
    partial void InsertInquiry(Inquiry instance);
    partial void UpdateInquiry(Inquiry instance);
    partial void DeleteInquiry(Inquiry instance);
    partial void InsertItemMst(ItemMst instance);
    partial void UpdateItemMst(ItemMst instance);
    partial void DeleteItemMst(ItemMst instance);
    partial void InsertProdMst(ProdMst instance);
    partial void UpdateProdMst(ProdMst instance);
    partial void DeleteProdMst(ProdMst instance);
    partial void InsertJewelTypeMst(JewelTypeMst instance);
    partial void UpdateJewelTypeMst(JewelTypeMst instance);
    partial void DeleteJewelTypeMst(JewelTypeMst instance);
    partial void InsertStoneQltyMst(StoneQltyMst instance);
    partial void UpdateStoneQltyMst(StoneQltyMst instance);
    partial void DeleteStoneQltyMst(StoneQltyMst instance);
    partial void InsertUserRegMst(UserRegMst instance);
    partial void UpdateUserRegMst(UserRegMst instance);
    partial void DeleteUserRegMst(UserRegMst instance);
    #endregion
		
		public dataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Project_demoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AdminLoginMst> AdminLoginMsts
		{
			get
			{
				return this.GetTable<AdminLoginMst>();
			}
		}
		
		public System.Data.Linq.Table<BrandMst> BrandMsts
		{
			get
			{
				return this.GetTable<BrandMst>();
			}
		}
		
		public System.Data.Linq.Table<CartList> CartLists
		{
			get
			{
				return this.GetTable<CartList>();
			}
		}
		
		public System.Data.Linq.Table<CatMst> CatMsts
		{
			get
			{
				return this.GetTable<CatMst>();
			}
		}
		
		public System.Data.Linq.Table<CertifyMst> CertifyMsts
		{
			get
			{
				return this.GetTable<CertifyMst>();
			}
		}
		
		public System.Data.Linq.Table<DimInfoMst> DimInfoMsts
		{
			get
			{
				return this.GetTable<DimInfoMst>();
			}
		}
		
		public System.Data.Linq.Table<DimMst> DimMsts
		{
			get
			{
				return this.GetTable<DimMst>();
			}
		}
		
		public System.Data.Linq.Table<DimQltyMst> DimQltyMsts
		{
			get
			{
				return this.GetTable<DimQltyMst>();
			}
		}
		
		public System.Data.Linq.Table<DimQltySubMst> DimQltySubMsts
		{
			get
			{
				return this.GetTable<DimQltySubMst>();
			}
		}
		
		public System.Data.Linq.Table<GoldKrtMst> GoldKrtMsts
		{
			get
			{
				return this.GetTable<GoldKrtMst>();
			}
		}
		
		public System.Data.Linq.Table<Inquiry> Inquiries
		{
			get
			{
				return this.GetTable<Inquiry>();
			}
		}
		
		public System.Data.Linq.Table<ItemMst> ItemMsts
		{
			get
			{
				return this.GetTable<ItemMst>();
			}
		}
		
		public System.Data.Linq.Table<ProdMst> ProdMsts
		{
			get
			{
				return this.GetTable<ProdMst>();
			}
		}
		
		public System.Data.Linq.Table<JewelTypeMst> JewelTypeMsts
		{
			get
			{
				return this.GetTable<JewelTypeMst>();
			}
		}
		
		public System.Data.Linq.Table<StoneMst> StoneMsts
		{
			get
			{
				return this.GetTable<StoneMst>();
			}
		}
		
		public System.Data.Linq.Table<StoneQltyMst> StoneQltyMsts
		{
			get
			{
				return this.GetTable<StoneQltyMst>();
			}
		}
		
		public System.Data.Linq.Table<UserRegMst> UserRegMsts
		{
			get
			{
				return this.GetTable<UserRegMst>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminLoginMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class AdminLoginMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public AdminLoginMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BrandMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class BrandMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Brand_ID;
		
		private string _Brand_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBrand_IDChanging(string value);
    partial void OnBrand_IDChanged();
    partial void OnBrand_TypeChanging(string value);
    partial void OnBrand_TypeChanged();
    #endregion
		
		public BrandMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Brand_ID
		{
			get
			{
				return this._Brand_ID;
			}
			set
			{
				if ((this._Brand_ID != value))
				{
					this.OnBrand_IDChanging(value);
					this.SendPropertyChanging();
					this._Brand_ID = value;
					this.SendPropertyChanged("Brand_ID");
					this.OnBrand_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Brand_Type
		{
			get
			{
				return this._Brand_Type;
			}
			set
			{
				if ((this._Brand_Type != value))
				{
					this.OnBrand_TypeChanging(value);
					this.SendPropertyChanging();
					this._Brand_Type = value;
					this.SendPropertyChanged("Brand_Type");
					this.OnBrand_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CartList")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CartList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Product_Name;
		
		private decimal _MRP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnProduct_NameChanging(string value);
    partial void OnProduct_NameChanged();
    partial void OnMRPChanging(decimal value);
    partial void OnMRPChanged();
    #endregion
		
		public CartList()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Product_Name
		{
			get
			{
				return this._Product_Name;
			}
			set
			{
				if ((this._Product_Name != value))
				{
					this.OnProduct_NameChanging(value);
					this.SendPropertyChanging();
					this._Product_Name = value;
					this.SendPropertyChanged("Product_Name");
					this.OnProduct_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal MRP
		{
			get
			{
				return this._MRP;
			}
			set
			{
				if ((this._MRP != value))
				{
					this.OnMRPChanging(value);
					this.SendPropertyChanging();
					this._MRP = value;
					this.SendPropertyChanged("MRP");
					this.OnMRPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CatMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cat_ID;
		
		private string _Cat_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCat_IDChanging(string value);
    partial void OnCat_IDChanged();
    partial void OnCat_NameChanging(string value);
    partial void OnCat_NameChanged();
    #endregion
		
		public CatMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this.OnCat_IDChanging(value);
					this.SendPropertyChanging();
					this._Cat_ID = value;
					this.SendPropertyChanged("Cat_ID");
					this.OnCat_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Cat_Name
		{
			get
			{
				return this._Cat_Name;
			}
			set
			{
				if ((this._Cat_Name != value))
				{
					this.OnCat_NameChanging(value);
					this.SendPropertyChanging();
					this._Cat_Name = value;
					this.SendPropertyChanged("Cat_Name");
					this.OnCat_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CertifyMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class CertifyMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Certify_ID;
		
		private string _Certify_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCertify_IDChanging(string value);
    partial void OnCertify_IDChanged();
    partial void OnCertify_TypeChanging(string value);
    partial void OnCertify_TypeChanged();
    #endregion
		
		public CertifyMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certify_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Certify_ID
		{
			get
			{
				return this._Certify_ID;
			}
			set
			{
				if ((this._Certify_ID != value))
				{
					this.OnCertify_IDChanging(value);
					this.SendPropertyChanging();
					this._Certify_ID = value;
					this.SendPropertyChanged("Certify_ID");
					this.OnCertify_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certify_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Certify_Type
		{
			get
			{
				return this._Certify_Type;
			}
			set
			{
				if ((this._Certify_Type != value))
				{
					this.OnCertify_TypeChanging(value);
					this.SendPropertyChanging();
					this._Certify_Type = value;
					this.SendPropertyChanged("Certify_Type");
					this.OnCertify_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimInfoMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DimInfoMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DimID;
		
		private string _DimType;
		
		private string _DimSubType;
		
		private string _DimCrt;
		
		private string _DimPrice;
		
		private string _DimImg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDimIDChanging(string value);
    partial void OnDimIDChanged();
    partial void OnDimTypeChanging(string value);
    partial void OnDimTypeChanged();
    partial void OnDimSubTypeChanging(string value);
    partial void OnDimSubTypeChanged();
    partial void OnDimCrtChanging(string value);
    partial void OnDimCrtChanged();
    partial void OnDimPriceChanging(string value);
    partial void OnDimPriceChanged();
    partial void OnDimImgChanging(string value);
    partial void OnDimImgChanged();
    #endregion
		
		public DimInfoMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string DimID
		{
			get
			{
				return this._DimID;
			}
			set
			{
				if ((this._DimID != value))
				{
					this.OnDimIDChanging(value);
					this.SendPropertyChanging();
					this._DimID = value;
					this.SendPropertyChanged("DimID");
					this.OnDimIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string DimType
		{
			get
			{
				return this._DimType;
			}
			set
			{
				if ((this._DimType != value))
				{
					this.OnDimTypeChanging(value);
					this.SendPropertyChanging();
					this._DimType = value;
					this.SendPropertyChanged("DimType");
					this.OnDimTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimSubType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string DimSubType
		{
			get
			{
				return this._DimSubType;
			}
			set
			{
				if ((this._DimSubType != value))
				{
					this.OnDimSubTypeChanging(value);
					this.SendPropertyChanging();
					this._DimSubType = value;
					this.SendPropertyChanged("DimSubType");
					this.OnDimSubTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimCrt", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string DimCrt
		{
			get
			{
				return this._DimCrt;
			}
			set
			{
				if ((this._DimCrt != value))
				{
					this.OnDimCrtChanging(value);
					this.SendPropertyChanging();
					this._DimCrt = value;
					this.SendPropertyChanged("DimCrt");
					this.OnDimCrtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimPrice", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string DimPrice
		{
			get
			{
				return this._DimPrice;
			}
			set
			{
				if ((this._DimPrice != value))
				{
					this.OnDimPriceChanging(value);
					this.SendPropertyChanging();
					this._DimPrice = value;
					this.SendPropertyChanged("DimPrice");
					this.OnDimPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimImg", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string DimImg
		{
			get
			{
				return this._DimImg;
			}
			set
			{
				if ((this._DimImg != value))
				{
					this.OnDimImgChanging(value);
					this.SendPropertyChanging();
					this._DimImg = value;
					this.SendPropertyChanged("DimImg");
					this.OnDimImgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DimMst
	{
		
		private string _Style_Code;
		
		private string _DimQlty_ID;
		
		private string _DimSubType_ID;
		
		private decimal _Dim_Crt;
		
		private decimal _Dim_Pcs;
		
		private decimal _Dim_Gm;
		
		private decimal _Dim_Size;
		
		private decimal _Dim_Rate;
		
		private decimal _Dim_Amt;
		
		public DimMst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Style_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Style_Code
		{
			get
			{
				return this._Style_Code;
			}
			set
			{
				if ((this._Style_Code != value))
				{
					this._Style_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimQlty_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string DimQlty_ID
		{
			get
			{
				return this._DimQlty_ID;
			}
			set
			{
				if ((this._DimQlty_ID != value))
				{
					this._DimQlty_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimSubType_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string DimSubType_ID
		{
			get
			{
				return this._DimSubType_ID;
			}
			set
			{
				if ((this._DimSubType_ID != value))
				{
					this._DimSubType_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Crt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal Dim_Crt
		{
			get
			{
				return this._Dim_Crt;
			}
			set
			{
				if ((this._Dim_Crt != value))
				{
					this._Dim_Crt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Pcs", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public decimal Dim_Pcs
		{
			get
			{
				return this._Dim_Pcs;
			}
			set
			{
				if ((this._Dim_Pcs != value))
				{
					this._Dim_Pcs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Gm", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public decimal Dim_Gm
		{
			get
			{
				return this._Dim_Gm;
			}
			set
			{
				if ((this._Dim_Gm != value))
				{
					this._Dim_Gm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Size", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public decimal Dim_Size
		{
			get
			{
				return this._Dim_Size;
			}
			set
			{
				if ((this._Dim_Size != value))
				{
					this._Dim_Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Rate", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public decimal Dim_Rate
		{
			get
			{
				return this._Dim_Rate;
			}
			set
			{
				if ((this._Dim_Rate != value))
				{
					this._Dim_Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dim_Amt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public decimal Dim_Amt
		{
			get
			{
				return this._Dim_Amt;
			}
			set
			{
				if ((this._Dim_Amt != value))
				{
					this._Dim_Amt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimQltyMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DimQltyMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DimQlty_ID;
		
		private string _DimQlty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDimQlty_IDChanging(string value);
    partial void OnDimQlty_IDChanged();
    partial void OnDimQltyChanging(string value);
    partial void OnDimQltyChanged();
    #endregion
		
		public DimQltyMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimQlty_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string DimQlty_ID
		{
			get
			{
				return this._DimQlty_ID;
			}
			set
			{
				if ((this._DimQlty_ID != value))
				{
					this.OnDimQlty_IDChanging(value);
					this.SendPropertyChanging();
					this._DimQlty_ID = value;
					this.SendPropertyChanged("DimQlty_ID");
					this.OnDimQlty_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimQlty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string DimQlty
		{
			get
			{
				return this._DimQlty;
			}
			set
			{
				if ((this._DimQlty != value))
				{
					this.OnDimQltyChanging(value);
					this.SendPropertyChanging();
					this._DimQlty = value;
					this.SendPropertyChanged("DimQlty");
					this.OnDimQltyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DimQltySubMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DimQltySubMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DimSubType_ID;
		
		private string _DimQlty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDimSubType_IDChanging(string value);
    partial void OnDimSubType_IDChanged();
    partial void OnDimQltyChanging(string value);
    partial void OnDimQltyChanged();
    #endregion
		
		public DimQltySubMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimSubType_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string DimSubType_ID
		{
			get
			{
				return this._DimSubType_ID;
			}
			set
			{
				if ((this._DimSubType_ID != value))
				{
					this.OnDimSubType_IDChanging(value);
					this.SendPropertyChanging();
					this._DimSubType_ID = value;
					this.SendPropertyChanged("DimSubType_ID");
					this.OnDimSubType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimQlty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string DimQlty
		{
			get
			{
				return this._DimQlty;
			}
			set
			{
				if ((this._DimQlty != value))
				{
					this.OnDimQltyChanging(value);
					this.SendPropertyChanging();
					this._DimQlty = value;
					this.SendPropertyChanged("DimQlty");
					this.OnDimQltyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GoldKrtMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class GoldKrtMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GoldType_ID;
		
		private string _Gold_Crt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGoldType_IDChanging(string value);
    partial void OnGoldType_IDChanged();
    partial void OnGold_CrtChanging(string value);
    partial void OnGold_CrtChanged();
    #endregion
		
		public GoldKrtMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoldType_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string GoldType_ID
		{
			get
			{
				return this._GoldType_ID;
			}
			set
			{
				if ((this._GoldType_ID != value))
				{
					this.OnGoldType_IDChanging(value);
					this.SendPropertyChanging();
					this._GoldType_ID = value;
					this.SendPropertyChanged("GoldType_ID");
					this.OnGoldType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Crt", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Gold_Crt
		{
			get
			{
				return this._Gold_Crt;
			}
			set
			{
				if ((this._Gold_Crt != value))
				{
					this.OnGold_CrtChanging(value);
					this.SendPropertyChanging();
					this._Gold_Crt = value;
					this.SendPropertyChanged("Gold_Crt");
					this.OnGold_CrtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inquiry")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class Inquiry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Name;
		
		private string _City;
		
		private string _Contact;
		
		private string _EmailID;
		
		private string _Comment;
		
		private System.DateTime _Cdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnEmailIDChanging(string value);
    partial void OnEmailIDChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnCdateChanging(System.DateTime value);
    partial void OnCdateChanged();
    #endregion
		
		public Inquiry()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string EmailID
		{
			get
			{
				return this._EmailID;
			}
			set
			{
				if ((this._EmailID != value))
				{
					this.OnEmailIDChanging(value);
					this.SendPropertyChanging();
					this._EmailID = value;
					this.SendPropertyChanged("EmailID");
					this.OnEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cdate", DbType="Date NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.DateTime Cdate
		{
			get
			{
				return this._Cdate;
			}
			set
			{
				if ((this._Cdate != value))
				{
					this.OnCdateChanging(value);
					this.SendPropertyChanging();
					this._Cdate = value;
					this.SendPropertyChanged("Cdate");
					this.OnCdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ItemMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Style_Code;
		
		private decimal _Pairs;
		
		private string _Brand_ID;
		
		private decimal _Quantity;
		
		private string _Cat_ID;
		
		private string _Prod_Quality;
		
		private string _Certify_ID;
		
		private string _Prod_ID;
		
		private string _GoldType_ID;
		
		private decimal _Gold_Wt;
		
		private decimal _Stone_Wt;
		
		private decimal _Net_Gold;
		
		private decimal _Wstg_Per;
		
		private decimal _Wstg;
		
		private decimal _Tot_Gross_Wt;
		
		private decimal _Gold_Rate;
		
		private decimal _Gold_Amt;
		
		private decimal _Gold_Making;
		
		private decimal _Stone_Making;
		
		private decimal _Other_Making;
		
		private decimal _Tot_Making;
		
		private decimal _MRP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStyle_CodeChanging(string value);
    partial void OnStyle_CodeChanged();
    partial void OnPairsChanging(decimal value);
    partial void OnPairsChanged();
    partial void OnBrand_IDChanging(string value);
    partial void OnBrand_IDChanged();
    partial void OnQuantityChanging(decimal value);
    partial void OnQuantityChanged();
    partial void OnCat_IDChanging(string value);
    partial void OnCat_IDChanged();
    partial void OnProd_QualityChanging(string value);
    partial void OnProd_QualityChanged();
    partial void OnCertify_IDChanging(string value);
    partial void OnCertify_IDChanged();
    partial void OnProd_IDChanging(string value);
    partial void OnProd_IDChanged();
    partial void OnGoldType_IDChanging(string value);
    partial void OnGoldType_IDChanged();
    partial void OnGold_WtChanging(decimal value);
    partial void OnGold_WtChanged();
    partial void OnStone_WtChanging(decimal value);
    partial void OnStone_WtChanged();
    partial void OnNet_GoldChanging(decimal value);
    partial void OnNet_GoldChanged();
    partial void OnWstg_PerChanging(decimal value);
    partial void OnWstg_PerChanged();
    partial void OnWstgChanging(decimal value);
    partial void OnWstgChanged();
    partial void OnTot_Gross_WtChanging(decimal value);
    partial void OnTot_Gross_WtChanged();
    partial void OnGold_RateChanging(decimal value);
    partial void OnGold_RateChanged();
    partial void OnGold_AmtChanging(decimal value);
    partial void OnGold_AmtChanged();
    partial void OnGold_MakingChanging(decimal value);
    partial void OnGold_MakingChanged();
    partial void OnStone_MakingChanging(decimal value);
    partial void OnStone_MakingChanged();
    partial void OnOther_MakingChanging(decimal value);
    partial void OnOther_MakingChanged();
    partial void OnTot_MakingChanging(decimal value);
    partial void OnTot_MakingChanged();
    partial void OnMRPChanging(decimal value);
    partial void OnMRPChanged();
    #endregion
		
		public ItemMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Style_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Style_Code
		{
			get
			{
				return this._Style_Code;
			}
			set
			{
				if ((this._Style_Code != value))
				{
					this.OnStyle_CodeChanging(value);
					this.SendPropertyChanging();
					this._Style_Code = value;
					this.SendPropertyChanged("Style_Code");
					this.OnStyle_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pairs", DbType="Decimal(3,0) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public decimal Pairs
		{
			get
			{
				return this._Pairs;
			}
			set
			{
				if ((this._Pairs != value))
				{
					this.OnPairsChanging(value);
					this.SendPropertyChanging();
					this._Pairs = value;
					this.SendPropertyChanged("Pairs");
					this.OnPairsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Brand_ID
		{
			get
			{
				return this._Brand_ID;
			}
			set
			{
				if ((this._Brand_ID != value))
				{
					this.OnBrand_IDChanging(value);
					this.SendPropertyChanging();
					this._Brand_ID = value;
					this.SendPropertyChanged("Brand_ID");
					this.OnBrand_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,0) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this.OnCat_IDChanging(value);
					this.SendPropertyChanging();
					this._Cat_ID = value;
					this.SendPropertyChanged("Cat_ID");
					this.OnCat_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Quality", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Prod_Quality
		{
			get
			{
				return this._Prod_Quality;
			}
			set
			{
				if ((this._Prod_Quality != value))
				{
					this.OnProd_QualityChanging(value);
					this.SendPropertyChanging();
					this._Prod_Quality = value;
					this.SendPropertyChanged("Prod_Quality");
					this.OnProd_QualityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certify_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Certify_ID
		{
			get
			{
				return this._Certify_ID;
			}
			set
			{
				if ((this._Certify_ID != value))
				{
					this.OnCertify_IDChanging(value);
					this.SendPropertyChanging();
					this._Certify_ID = value;
					this.SendPropertyChanged("Certify_ID");
					this.OnCertify_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this.OnProd_IDChanging(value);
					this.SendPropertyChanging();
					this._Prod_ID = value;
					this.SendPropertyChanged("Prod_ID");
					this.OnProd_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoldType_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string GoldType_ID
		{
			get
			{
				return this._GoldType_ID;
			}
			set
			{
				if ((this._GoldType_ID != value))
				{
					this.OnGoldType_IDChanging(value);
					this.SendPropertyChanging();
					this._GoldType_ID = value;
					this.SendPropertyChanged("GoldType_ID");
					this.OnGoldType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Wt", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public decimal Gold_Wt
		{
			get
			{
				return this._Gold_Wt;
			}
			set
			{
				if ((this._Gold_Wt != value))
				{
					this.OnGold_WtChanging(value);
					this.SendPropertyChanging();
					this._Gold_Wt = value;
					this.SendPropertyChanged("Gold_Wt");
					this.OnGold_WtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Wt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public decimal Stone_Wt
		{
			get
			{
				return this._Stone_Wt;
			}
			set
			{
				if ((this._Stone_Wt != value))
				{
					this.OnStone_WtChanging(value);
					this.SendPropertyChanging();
					this._Stone_Wt = value;
					this.SendPropertyChanged("Stone_Wt");
					this.OnStone_WtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_Gold", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public decimal Net_Gold
		{
			get
			{
				return this._Net_Gold;
			}
			set
			{
				if ((this._Net_Gold != value))
				{
					this.OnNet_GoldChanging(value);
					this.SendPropertyChanging();
					this._Net_Gold = value;
					this.SendPropertyChanged("Net_Gold");
					this.OnNet_GoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wstg_Per", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public decimal Wstg_Per
		{
			get
			{
				return this._Wstg_Per;
			}
			set
			{
				if ((this._Wstg_Per != value))
				{
					this.OnWstg_PerChanging(value);
					this.SendPropertyChanging();
					this._Wstg_Per = value;
					this.SendPropertyChanged("Wstg_Per");
					this.OnWstg_PerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wstg", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public decimal Wstg
		{
			get
			{
				return this._Wstg;
			}
			set
			{
				if ((this._Wstg != value))
				{
					this.OnWstgChanging(value);
					this.SendPropertyChanging();
					this._Wstg = value;
					this.SendPropertyChanged("Wstg");
					this.OnWstgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Gross_Wt", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public decimal Tot_Gross_Wt
		{
			get
			{
				return this._Tot_Gross_Wt;
			}
			set
			{
				if ((this._Tot_Gross_Wt != value))
				{
					this.OnTot_Gross_WtChanging(value);
					this.SendPropertyChanging();
					this._Tot_Gross_Wt = value;
					this.SendPropertyChanged("Tot_Gross_Wt");
					this.OnTot_Gross_WtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Rate", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public decimal Gold_Rate
		{
			get
			{
				return this._Gold_Rate;
			}
			set
			{
				if ((this._Gold_Rate != value))
				{
					this.OnGold_RateChanging(value);
					this.SendPropertyChanging();
					this._Gold_Rate = value;
					this.SendPropertyChanged("Gold_Rate");
					this.OnGold_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Amt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public decimal Gold_Amt
		{
			get
			{
				return this._Gold_Amt;
			}
			set
			{
				if ((this._Gold_Amt != value))
				{
					this.OnGold_AmtChanging(value);
					this.SendPropertyChanging();
					this._Gold_Amt = value;
					this.SendPropertyChanged("Gold_Amt");
					this.OnGold_AmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public decimal Gold_Making
		{
			get
			{
				return this._Gold_Making;
			}
			set
			{
				if ((this._Gold_Making != value))
				{
					this.OnGold_MakingChanging(value);
					this.SendPropertyChanging();
					this._Gold_Making = value;
					this.SendPropertyChanged("Gold_Making");
					this.OnGold_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public decimal Stone_Making
		{
			get
			{
				return this._Stone_Making;
			}
			set
			{
				if ((this._Stone_Making != value))
				{
					this.OnStone_MakingChanging(value);
					this.SendPropertyChanging();
					this._Stone_Making = value;
					this.SendPropertyChanged("Stone_Making");
					this.OnStone_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public decimal Other_Making
		{
			get
			{
				return this._Other_Making;
			}
			set
			{
				if ((this._Other_Making != value))
				{
					this.OnOther_MakingChanging(value);
					this.SendPropertyChanging();
					this._Other_Making = value;
					this.SendPropertyChanged("Other_Making");
					this.OnOther_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public decimal Tot_Making
		{
			get
			{
				return this._Tot_Making;
			}
			set
			{
				if ((this._Tot_Making != value))
				{
					this.OnTot_MakingChanging(value);
					this.SendPropertyChanging();
					this._Tot_Making = value;
					this.SendPropertyChanged("Tot_Making");
					this.OnTot_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public decimal MRP
		{
			get
			{
				return this._MRP;
			}
			set
			{
				if ((this._MRP != value))
				{
					this.OnMRPChanging(value);
					this.SendPropertyChanging();
					this._MRP = value;
					this.SendPropertyChanged("MRP");
					this.OnMRPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProdMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ProdMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Prod_ID;
		
		private string _Prod_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProd_IDChanging(string value);
    partial void OnProd_IDChanged();
    partial void OnProd_TypeChanging(string value);
    partial void OnProd_TypeChanged();
    #endregion
		
		public ProdMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this.OnProd_IDChanging(value);
					this.SendPropertyChanging();
					this._Prod_ID = value;
					this.SendPropertyChanged("Prod_ID");
					this.OnProd_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Prod_Type
		{
			get
			{
				return this._Prod_Type;
			}
			set
			{
				if ((this._Prod_Type != value))
				{
					this.OnProd_TypeChanging(value);
					this.SendPropertyChanging();
					this._Prod_Type = value;
					this.SendPropertyChanged("Prod_Type");
					this.OnProd_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JewelTypeMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class JewelTypeMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Jewellery_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnJewellery_TypeChanging(string value);
    partial void OnJewellery_TypeChanged();
    #endregion
		
		public JewelTypeMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jewellery_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string Jewellery_Type
		{
			get
			{
				return this._Jewellery_Type;
			}
			set
			{
				if ((this._Jewellery_Type != value))
				{
					this.OnJewellery_TypeChanging(value);
					this.SendPropertyChanging();
					this._Jewellery_Type = value;
					this.SendPropertyChanged("Jewellery_Type");
					this.OnJewellery_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoneMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class StoneMst
	{
		
		private string _Style_Code;
		
		private string _StoneQlty_ID;
		
		private decimal _Stone_Gm;
		
		private decimal _Stone_Pcs;
		
		private decimal _Stone_Crt;
		
		private decimal _Stone_Rate;
		
		private decimal _Stone_Amt;
		
		public StoneMst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Style_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Style_Code
		{
			get
			{
				return this._Style_Code;
			}
			set
			{
				if ((this._Style_Code != value))
				{
					this._Style_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoneQlty_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string StoneQlty_ID
		{
			get
			{
				return this._StoneQlty_ID;
			}
			set
			{
				if ((this._StoneQlty_ID != value))
				{
					this._StoneQlty_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Gm", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal Stone_Gm
		{
			get
			{
				return this._Stone_Gm;
			}
			set
			{
				if ((this._Stone_Gm != value))
				{
					this._Stone_Gm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Pcs", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal Stone_Pcs
		{
			get
			{
				return this._Stone_Pcs;
			}
			set
			{
				if ((this._Stone_Pcs != value))
				{
					this._Stone_Pcs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Crt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public decimal Stone_Crt
		{
			get
			{
				return this._Stone_Crt;
			}
			set
			{
				if ((this._Stone_Crt != value))
				{
					this._Stone_Crt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Rate", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public decimal Stone_Rate
		{
			get
			{
				return this._Stone_Rate;
			}
			set
			{
				if ((this._Stone_Rate != value))
				{
					this._Stone_Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Amt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public decimal Stone_Amt
		{
			get
			{
				return this._Stone_Amt;
			}
			set
			{
				if ((this._Stone_Amt != value))
				{
					this._Stone_Amt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoneQltyMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class StoneQltyMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StoneQlty_ID;
		
		private string _StoneQlty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStoneQlty_IDChanging(string value);
    partial void OnStoneQlty_IDChanged();
    partial void OnStoneQltyChanging(string value);
    partial void OnStoneQltyChanged();
    #endregion
		
		public StoneQltyMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoneQlty_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string StoneQlty_ID
		{
			get
			{
				return this._StoneQlty_ID;
			}
			set
			{
				if ((this._StoneQlty_ID != value))
				{
					this.OnStoneQlty_IDChanging(value);
					this.SendPropertyChanging();
					this._StoneQlty_ID = value;
					this.SendPropertyChanged("StoneQlty_ID");
					this.OnStoneQlty_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoneQlty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string StoneQlty
		{
			get
			{
				return this._StoneQlty;
			}
			set
			{
				if ((this._StoneQlty != value))
				{
					this.OnStoneQltyChanging(value);
					this.SendPropertyChanging();
					this._StoneQlty = value;
					this.SendPropertyChanged("StoneQlty");
					this.OnStoneQltyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserRegMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class UserRegMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userID;
		
		private string _userFname;
		
		private string _userLname;
		
		private string _address;
		
		private string _city;
		
		private string _state;
		
		private string _mobNo;
		
		private string _emailID;
		
		private string _dob;
		
		private string _cdate;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnuserFnameChanging(string value);
    partial void OnuserFnameChanged();
    partial void OnuserLnameChanging(string value);
    partial void OnuserLnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnmobNoChanging(string value);
    partial void OnmobNoChanged();
    partial void OnemailIDChanging(string value);
    partial void OnemailIDChanged();
    partial void OndobChanging(string value);
    partial void OndobChanged();
    partial void OncdateChanging(string value);
    partial void OncdateChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public UserRegMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userFname", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string userFname
		{
			get
			{
				return this._userFname;
			}
			set
			{
				if ((this._userFname != value))
				{
					this.OnuserFnameChanging(value);
					this.SendPropertyChanging();
					this._userFname = value;
					this.SendPropertyChanged("userFname");
					this.OnuserFnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userLname", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string userLname
		{
			get
			{
				return this._userLname;
			}
			set
			{
				if ((this._userLname != value))
				{
					this.OnuserLnameChanging(value);
					this.SendPropertyChanging();
					this._userLname = value;
					this.SendPropertyChanged("userLname");
					this.OnuserLnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobNo", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string mobNo
		{
			get
			{
				return this._mobNo;
			}
			set
			{
				if ((this._mobNo != value))
				{
					this.OnmobNoChanging(value);
					this.SendPropertyChanging();
					this._mobNo = value;
					this.SendPropertyChanged("mobNo");
					this.OnmobNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailID", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string emailID
		{
			get
			{
				return this._emailID;
			}
			set
			{
				if ((this._emailID != value))
				{
					this.OnemailIDChanging(value);
					this.SendPropertyChanging();
					this._emailID = value;
					this.SendPropertyChanged("emailID");
					this.OnemailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdate", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public string cdate
		{
			get
			{
				return this._cdate;
			}
			set
			{
				if ((this._cdate != value))
				{
					this.OncdateChanging(value);
					this.SendPropertyChanging();
					this._cdate = value;
					this.SendPropertyChanged("cdate");
					this.OncdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
