//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jwelleryshopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldView
    {
        public int No { get; set; }
        public string Style_code { get; set; }
        public string GoldType_ID { get; set; }
        public string Gold_Crt { get; set; }
        public decimal Gold_Rate { get; set; }
        public decimal Gold_Wt { get; set; }
        public decimal Wstg_Per { get; set; }
        public decimal Wstq { get; set; }
        public decimal Total_weight { get; set; }
        public Nullable<decimal> PriceOnGram { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    }
}
