//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jwelleryshopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDisplayItem
    {
        public string Style_Code { get; set; }
        public string img { get; set; }
        public string image { get; set; }
        public Nullable<decimal> total_brand { get; set; }
    }
}
