#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jwelleryshopping.NewFolder1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Project_demo")]
	public partial class ItemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertItemMst(ItemMst instance);
    partial void UpdateItemMst(ItemMst instance);
    partial void DeleteItemMst(ItemMst instance);
    #endregion
		
		public ItemDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Project_demoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ItemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ItemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ItemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ItemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ItemMst> ItemMsts
		{
			get
			{
				return this.GetTable<ItemMst>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class ItemMst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Style_Code;
		
		private decimal _Pairs;
		
		private string _Brand_ID;
		
		private decimal _Quantity;
		
		private string _Cat_ID;
		
		private string _Prod_Quality;
		
		private string _Certify_ID;
		
		private string _Prod_ID;
		
		private string _GoldType_ID;
		
		private decimal _Gold_Wt;
		
		private decimal _Stone_Wt;
		
		private decimal _Net_Gold;
		
		private decimal _Wstg_Per;
		
		private decimal _Wstg;
		
		private decimal _Tot_Gross_Wt;
		
		private decimal _Gold_Rate;
		
		private decimal _Gold_Amt;
		
		private decimal _Gold_Making;
		
		private decimal _Stone_Making;
		
		private decimal _Other_Making;
		
		private decimal _Tot_Making;
		
		private decimal _MRP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStyle_CodeChanging(string value);
    partial void OnStyle_CodeChanged();
    partial void OnPairsChanging(decimal value);
    partial void OnPairsChanged();
    partial void OnBrand_IDChanging(string value);
    partial void OnBrand_IDChanged();
    partial void OnQuantityChanging(decimal value);
    partial void OnQuantityChanged();
    partial void OnCat_IDChanging(string value);
    partial void OnCat_IDChanged();
    partial void OnProd_QualityChanging(string value);
    partial void OnProd_QualityChanged();
    partial void OnCertify_IDChanging(string value);
    partial void OnCertify_IDChanged();
    partial void OnProd_IDChanging(string value);
    partial void OnProd_IDChanged();
    partial void OnGoldType_IDChanging(string value);
    partial void OnGoldType_IDChanged();
    partial void OnGold_WtChanging(decimal value);
    partial void OnGold_WtChanged();
    partial void OnStone_WtChanging(decimal value);
    partial void OnStone_WtChanged();
    partial void OnNet_GoldChanging(decimal value);
    partial void OnNet_GoldChanged();
    partial void OnWstg_PerChanging(decimal value);
    partial void OnWstg_PerChanged();
    partial void OnWstgChanging(decimal value);
    partial void OnWstgChanged();
    partial void OnTot_Gross_WtChanging(decimal value);
    partial void OnTot_Gross_WtChanged();
    partial void OnGold_RateChanging(decimal value);
    partial void OnGold_RateChanged();
    partial void OnGold_AmtChanging(decimal value);
    partial void OnGold_AmtChanged();
    partial void OnGold_MakingChanging(decimal value);
    partial void OnGold_MakingChanged();
    partial void OnStone_MakingChanging(decimal value);
    partial void OnStone_MakingChanged();
    partial void OnOther_MakingChanging(decimal value);
    partial void OnOther_MakingChanged();
    partial void OnTot_MakingChanging(decimal value);
    partial void OnTot_MakingChanged();
    partial void OnMRPChanging(decimal value);
    partial void OnMRPChanged();
    #endregion
		
		public ItemMst()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Style_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Style_Code
		{
			get
			{
				return this._Style_Code;
			}
			set
			{
				if ((this._Style_Code != value))
				{
					this.OnStyle_CodeChanging(value);
					this.SendPropertyChanging();
					this._Style_Code = value;
					this.SendPropertyChanged("Style_Code");
					this.OnStyle_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pairs", DbType="Decimal(3,0) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public decimal Pairs
		{
			get
			{
				return this._Pairs;
			}
			set
			{
				if ((this._Pairs != value))
				{
					this.OnPairsChanging(value);
					this.SendPropertyChanging();
					this._Pairs = value;
					this.SendPropertyChanged("Pairs");
					this.OnPairsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string Brand_ID
		{
			get
			{
				return this._Brand_ID;
			}
			set
			{
				if ((this._Brand_ID != value))
				{
					this.OnBrand_IDChanging(value);
					this.SendPropertyChanging();
					this._Brand_ID = value;
					this.SendPropertyChanged("Brand_ID");
					this.OnBrand_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,0) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this.OnCat_IDChanging(value);
					this.SendPropertyChanging();
					this._Cat_ID = value;
					this.SendPropertyChanged("Cat_ID");
					this.OnCat_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_Quality", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public string Prod_Quality
		{
			get
			{
				return this._Prod_Quality;
			}
			set
			{
				if ((this._Prod_Quality != value))
				{
					this.OnProd_QualityChanging(value);
					this.SendPropertyChanging();
					this._Prod_Quality = value;
					this.SendPropertyChanged("Prod_Quality");
					this.OnProd_QualityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certify_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public string Certify_ID
		{
			get
			{
				return this._Certify_ID;
			}
			set
			{
				if ((this._Certify_ID != value))
				{
					this.OnCertify_IDChanging(value);
					this.SendPropertyChanging();
					this._Certify_ID = value;
					this.SendPropertyChanged("Certify_ID");
					this.OnCertify_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this.OnProd_IDChanging(value);
					this.SendPropertyChanging();
					this._Prod_ID = value;
					this.SendPropertyChanged("Prod_ID");
					this.OnProd_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoldType_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=9)]
		public string GoldType_ID
		{
			get
			{
				return this._GoldType_ID;
			}
			set
			{
				if ((this._GoldType_ID != value))
				{
					this.OnGoldType_IDChanging(value);
					this.SendPropertyChanging();
					this._GoldType_ID = value;
					this.SendPropertyChanged("GoldType_ID");
					this.OnGoldType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Wt", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=10)]
		public decimal Gold_Wt
		{
			get
			{
				return this._Gold_Wt;
			}
			set
			{
				if ((this._Gold_Wt != value))
				{
					this.OnGold_WtChanging(value);
					this.SendPropertyChanging();
					this._Gold_Wt = value;
					this.SendPropertyChanged("Gold_Wt");
					this.OnGold_WtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Wt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=11)]
		public decimal Stone_Wt
		{
			get
			{
				return this._Stone_Wt;
			}
			set
			{
				if ((this._Stone_Wt != value))
				{
					this.OnStone_WtChanging(value);
					this.SendPropertyChanging();
					this._Stone_Wt = value;
					this.SendPropertyChanged("Stone_Wt");
					this.OnStone_WtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net_Gold", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=12)]
		public decimal Net_Gold
		{
			get
			{
				return this._Net_Gold;
			}
			set
			{
				if ((this._Net_Gold != value))
				{
					this.OnNet_GoldChanging(value);
					this.SendPropertyChanging();
					this._Net_Gold = value;
					this.SendPropertyChanged("Net_Gold");
					this.OnNet_GoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wstg_Per", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=13)]
		public decimal Wstg_Per
		{
			get
			{
				return this._Wstg_Per;
			}
			set
			{
				if ((this._Wstg_Per != value))
				{
					this.OnWstg_PerChanging(value);
					this.SendPropertyChanging();
					this._Wstg_Per = value;
					this.SendPropertyChanged("Wstg_Per");
					this.OnWstg_PerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wstg", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=14)]
		public decimal Wstg
		{
			get
			{
				return this._Wstg;
			}
			set
			{
				if ((this._Wstg != value))
				{
					this.OnWstgChanging(value);
					this.SendPropertyChanging();
					this._Wstg = value;
					this.SendPropertyChanged("Wstg");
					this.OnWstgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Gross_Wt", DbType="Decimal(10,3) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=15)]
		public decimal Tot_Gross_Wt
		{
			get
			{
				return this._Tot_Gross_Wt;
			}
			set
			{
				if ((this._Tot_Gross_Wt != value))
				{
					this.OnTot_Gross_WtChanging(value);
					this.SendPropertyChanging();
					this._Tot_Gross_Wt = value;
					this.SendPropertyChanged("Tot_Gross_Wt");
					this.OnTot_Gross_WtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Rate", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=16)]
		public decimal Gold_Rate
		{
			get
			{
				return this._Gold_Rate;
			}
			set
			{
				if ((this._Gold_Rate != value))
				{
					this.OnGold_RateChanging(value);
					this.SendPropertyChanging();
					this._Gold_Rate = value;
					this.SendPropertyChanged("Gold_Rate");
					this.OnGold_RateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Amt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=17)]
		public decimal Gold_Amt
		{
			get
			{
				return this._Gold_Amt;
			}
			set
			{
				if ((this._Gold_Amt != value))
				{
					this.OnGold_AmtChanging(value);
					this.SendPropertyChanging();
					this._Gold_Amt = value;
					this.SendPropertyChanged("Gold_Amt");
					this.OnGold_AmtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gold_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=18)]
		public decimal Gold_Making
		{
			get
			{
				return this._Gold_Making;
			}
			set
			{
				if ((this._Gold_Making != value))
				{
					this.OnGold_MakingChanging(value);
					this.SendPropertyChanging();
					this._Gold_Making = value;
					this.SendPropertyChanged("Gold_Making");
					this.OnGold_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=19)]
		public decimal Stone_Making
		{
			get
			{
				return this._Stone_Making;
			}
			set
			{
				if ((this._Stone_Making != value))
				{
					this.OnStone_MakingChanging(value);
					this.SendPropertyChanging();
					this._Stone_Making = value;
					this.SendPropertyChanged("Stone_Making");
					this.OnStone_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=20)]
		public decimal Other_Making
		{
			get
			{
				return this._Other_Making;
			}
			set
			{
				if ((this._Other_Making != value))
				{
					this.OnOther_MakingChanging(value);
					this.SendPropertyChanging();
					this._Other_Making = value;
					this.SendPropertyChanged("Other_Making");
					this.OnOther_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Making", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=21)]
		public decimal Tot_Making
		{
			get
			{
				return this._Tot_Making;
			}
			set
			{
				if ((this._Tot_Making != value))
				{
					this.OnTot_MakingChanging(value);
					this.SendPropertyChanging();
					this._Tot_Making = value;
					this.SendPropertyChanged("Tot_Making");
					this.OnTot_MakingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=22)]
		public decimal MRP
		{
			get
			{
				return this._MRP;
			}
			set
			{
				if ((this._MRP != value))
				{
					this.OnMRPChanging(value);
					this.SendPropertyChanging();
					this._MRP = value;
					this.SendPropertyChanged("MRP");
					this.OnMRPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
