#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jwelleryshopping.NewFolder1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Project_demo")]
	public partial class StoneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public StoneDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Project_demoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StoneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StoneMst> StoneMsts
		{
			get
			{
				return this.GetTable<StoneMst>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StoneMst")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class StoneMst
	{
		
		private string _Style_Code;
		
		private string _StoneQlty_ID;
		
		private decimal _Stone_Gm;
		
		private decimal _Stone_Pcs;
		
		private decimal _Stone_Crt;
		
		private decimal _Stone_Rate;
		
		private decimal _Stone_Amt;
		
		public StoneMst()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Style_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string Style_Code
		{
			get
			{
				return this._Style_Code;
			}
			set
			{
				if ((this._Style_Code != value))
				{
					this._Style_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoneQlty_ID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string StoneQlty_ID
		{
			get
			{
				return this._StoneQlty_ID;
			}
			set
			{
				if ((this._StoneQlty_ID != value))
				{
					this._StoneQlty_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Gm", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal Stone_Gm
		{
			get
			{
				return this._Stone_Gm;
			}
			set
			{
				if ((this._Stone_Gm != value))
				{
					this._Stone_Gm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Pcs", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal Stone_Pcs
		{
			get
			{
				return this._Stone_Pcs;
			}
			set
			{
				if ((this._Stone_Pcs != value))
				{
					this._Stone_Pcs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Crt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public decimal Stone_Crt
		{
			get
			{
				return this._Stone_Crt;
			}
			set
			{
				if ((this._Stone_Crt != value))
				{
					this._Stone_Crt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Rate", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public decimal Stone_Rate
		{
			get
			{
				return this._Stone_Rate;
			}
			set
			{
				if ((this._Stone_Rate != value))
				{
					this._Stone_Rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stone_Amt", DbType="Decimal(10,2) NOT NULL")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public decimal Stone_Amt
		{
			get
			{
				return this._Stone_Amt;
			}
			set
			{
				if ((this._Stone_Amt != value))
				{
					this._Stone_Amt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
